version: "3.7"

services:
  db:
    image: postgres
    container_name: strapi-postgres
    ports:
      - "6543:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      POSTGRES_DB: strapi

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8080"
