version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'directus'
      MYSQL_USER: 'directus'
      MYSQL_PASSWORD: 'directus'
      MYSQL_ROOT_PASSWORD: 'directus'
    ports:
      - '3307:3306'

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - '8081:80'
    environment:
      MYSQL_ROOT_PASSWORD: 'directus'
      MYSQL_USER: 'directus'
      MYSQL_PASSWORD: 'directus'
      PMA_HOST: 'mysql'

  directus:
    image: directus/directus:v8-apache
    ports:
      - '8080:80'
    environment:
      DIRECTUS_APP_ENV: 'production'
      DIRECTUS_AUTH_PUBLICKEY: 'some random secret'
      DIRECTUS_AUTH_SECRETKEY: 'another random secret'
      DIRECTUS_DATABASE_HOST: 'mysql'
      DIRECTUS_DATABASE_PORT: '3306'
      DIRECTUS_DATABASE_NAME: 'directus'
      DIRECTUS_DATABASE_USERNAME: 'directus'
      DIRECTUS_DATABASE_PASSWORD: 'directus'
    volumes:
      - ./data/config:/var/directus/config
      - ./data/uploads:/var/directus/public/uploads
    links:
      - mysql:mysql
